# Generated by Django 4.2.25 on 2025-11-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes')], default='clothing', max_length=20),
        ),
    ]
